### ISSUE TITLE
GOLD TODO List

### ISSUE THREAD

**Issue by Sama34** [Sama34/OUGC-Feedback#4]
There are still some changes I need to do before releasing this.
- [x] Move validation to validation method.
- [x] Proper throw_error method usage.
- [x] Write delete feature.
- [x] Write edit feature.
- [x] Add go back button to modal form.
- [x] There are settings that do nothing.
- [x] _Allow Thread Feedback_ settings should be moved to forum settings.
- [x] Remove _Allow Feedback Comments_ setting.
- [x] Remove _Enable The Report Center_ setting.
- [ ] ~~Allow users to select notification settings.~~

**Comment by Sama34** [comment]
Last one will be left split to #8
